
# Invokes sub-makefiles for mvrp program and mvrp (ipc) shared library.

all:
	$(MAKE) -f Makefile.lib all
	$(MAKE) -f Makefile.prg all

clean:
	$(MAKE) -f Makefile.lib clean
	$(MAKE) -f Makefile.prg clean

install:
	$(MAKE) -f Makefile.lib install
	$(MAKE) -f Makefile.prg install
