ROOTFS_OVERRIDE = $(WRS_BASE_DIR)/../userspace/rootfs_override

OBJS = mvrp_proxy.o

CC   = $(CROSS_COMPILE)gcc

# We must include stuff from various headers, which are installed.
# If this is build under build scripts, it's $WRS_OUTPUT_DIR/images/wr
WR_INSTALL_ROOT ?= /usr/lib/white-rabbit
WR_INCLUDE = $(WR_INSTALL_ROOT)/include
WR_LIB = $(WR_INSTALL_ROOT)/lib

CFLAGS  := -fPIC -shared -O2 -DDEBUG -Wall -ggdb -DTRACE_ALL \
           -I. -I../include -I../wrsw_rtud -I../wrsw_mrp -I$(WR_INCLUDE) \
           -I$(LINUX)/include

# -I$(CROSS_COMPILE_ARM_PATH)/../include

LDFLAGS := -fPIC -shared -L. -L$(WR_LIB) \
           -lwripc -lminipc

RM := rm -f

LIB  = libwrmvrp.so

all: $(LIB)

$(LIB): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

clean:
	$(RM) $(LIB) $(OBJS)

install: all
	install -d $(WR_INSTALL_ROOT)/lib
	install $(LIB) $(WR_INSTALL_ROOT)/lib
