/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ieee8021QBridgePortVlanTable.h"


/* column number definitions for table ieee8021QBridgePortVlanTable */
#define COLUMN_IEEE8021QBRIDGEPVID		1
#define COLUMN_IEEE8021QBRIDGEPORTACCEPTABLEFRAMETYPES		2
#define COLUMN_IEEE8021QBRIDGEPORTINGRESSFILTERING		3
#define COLUMN_IEEE8021QBRIDGEPORTMVRPENABLEDSTATUS		4
#define COLUMN_IEEE8021QBRIDGEPORTMVRPFAILEDREGISTRATIONS		5
#define COLUMN_IEEE8021QBRIDGEPORTMVRPLASTPDUORIGIN		6
#define COLUMN_IEEE8021QBRIDGEPORTRESTRICTEDVLANREGISTRATION		7

    /* Typical data structure for a row entry */
struct ieee8021QBridgePortVlanTable_entry {
    /* Index values */
    u_long ieee8021BridgeBasePortComponentId;
    u_long ieee8021BridgeBasePort;

    /* Column values */
    u_long ieee8021QBridgePvid;
    u_long old_ieee8021QBridgePvid;
    long ieee8021QBridgePortAcceptableFrameTypes;
    long old_ieee8021QBridgePortAcceptableFrameTypes;
    long ieee8021QBridgePortIngressFiltering;
    long old_ieee8021QBridgePortIngressFiltering;
    long ieee8021QBridgePortMvrpEnabledStatus;
    long old_ieee8021QBridgePortMvrpEnabledStatus;
    U64 ieee8021QBridgePortMvrpFailedRegistrations;
    char ieee8021QBridgePortMvrpLastPduOrigin[NNN];
    size_t ieee8021QBridgePortMvrpLastPduOrigin_len;
    long ieee8021QBridgePortRestrictedVlanRegistration;
    long old_ieee8021QBridgePortRestrictedVlanRegistration;

    int   valid;
};

/* create a new row in the table */
static struct ieee8021QBridgePortVlanTable_entry *
ieee8021QBridgePortVlanTable_createEntry( int dummy
                 , u_long  ieee8021BridgeBasePortComponentId
                 , u_long  ieee8021BridgeBasePort
                ) {
    struct ieee8021QBridgePortVlanTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct ieee8021QBridgePortVlanTable_entry);
    if (!entry)
        return NULL;

    /* XXX - insert entry into local data structure */
    return entry;
}

/* remove a row from the table */
static void
ieee8021QBridgePortVlanTable_removeEntry(struct ieee8021QBridgePortVlanTable_entry *entry) {
    if (!entry)
        return;    /* Nothing to remove */

    /* XXX - remove entry from local data structure */

    if (entry)
        SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/** determine the appropriate row for an exact request */
static struct ieee8021QBridgePortVlanTable_entry *
ieee8021QBridgePortVlanTable_get_entry( netsnmp_variable_list *indexes ) {
    struct ieee8021QBridgePortVlanTable_entry *row = NULL;

    /* XXX - Use the 'indexes' parameter to retrieve the data
       structure for the requested row, and return this. */
    return row;
}

/** determine the appropriate row for an fuzzy request */
static struct ieee8021QBridgePortVlanTable_entry *
ieee8021QBridgePortVlanTable_get_next_entry( netsnmp_handler_registration *reginfo,
                     netsnmp_request_info         *request,
                     int                           column,
                     netsnmp_variable_list        *indexes ) {
    struct ieee8021QBridgePortVlanTable_entry *row = NULL;
    oid             build_space[MAX_OID_LEN];
    size_t          build_space_len = 0;
    size_t          index_oid_len = 0;

    /* XXX - Use the 'indexes' parameter to identify the
             next row in the table.... */

    /* XXX   .... update the 'indexes' parameter with the
             appropriate index values ... */

    /* ... and update the requested OID to match this instance */
    memcpy(build_space, reginfo->rootoid,   /* registered oid */
                        reginfo->rootoid_len * sizeof(oid));
    build_space_len = reginfo->rootoid_len;
    build_space[build_space_len++] = 1;  /* entry */
    build_space[build_space_len++] = column; /* column */
    build_oid_noalloc(build_space + build_space_len,
                      MAX_OID_LEN - build_space_len, &index_oid_len,
                      NULL, 0, indexes);
    snmp_set_var_objid(request->requestvb, build_space,
                       build_space_len + index_oid_len);

    /*  Finally, return the data structure for this row */
    return row;
}


/** handles requests for the ieee8021QBridgePortVlanTable table */
static int
ieee8021QBridgePortVlanTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct ieee8021QBridgePortVlanTable_entry          *table_entry;
    int                         ret;

    switch (reqinfo->mode) {
        /*
         * Read-support
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     ieee8021QBridgePortVlanTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021QBRIDGEPVID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->ieee8021QBridgePvid);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTACCEPTABLEFRAMETYPES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortAcceptableFrameTypes);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTINGRESSFILTERING:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortIngressFiltering);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPENABLEDSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortMvrpEnabledStatus);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPFAILEDREGISTRATIONS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER64,
                                            table_entry->ieee8021QBridgePortMvrpFailedRegistrations);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPLASTPDUORIGIN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ieee8021QBridgePortMvrpLastPduOrigin,
                                          table_entry->ieee8021QBridgePortMvrpLastPduOrigin_len);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTRESTRICTEDVLANREGISTRATION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortRestrictedVlanRegistration);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    case MODE_GETNEXT:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     ieee8021QBridgePortVlanTable_get_next_entry( reginfo, request,
                                   table_info->colnum, table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021QBRIDGEPVID:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_UNSIGNED,
                                            table_entry->ieee8021QBridgePvid);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTACCEPTABLEFRAMETYPES:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortAcceptableFrameTypes);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTINGRESSFILTERING:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortIngressFiltering);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPENABLEDSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortMvrpEnabledStatus);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPFAILEDREGISTRATIONS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_COUNTER64,
                                            table_entry->ieee8021QBridgePortMvrpFailedRegistrations);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPLASTPDUORIGIN:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ieee8021QBridgePortMvrpLastPduOrigin,
                                          table_entry->ieee8021QBridgePortMvrpLastPduOrigin_len);
                break;
            case COLUMN_IEEE8021QBRIDGEPORTRESTRICTEDVLANREGISTRATION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ieee8021QBridgePortRestrictedVlanRegistration);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     ieee8021QBridgePortVlanTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021QBRIDGEPVID:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_IEEE8021QBRIDGEPORTACCEPTABLEFRAMETYPES:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_IEEE8021QBRIDGEPORTINGRESSFILTERING:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPENABLEDSTATUS:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            case COLUMN_IEEE8021QBRIDGEPORTRESTRICTEDVLANREGISTRATION:
                /* or possibly 'netsnmp_check_vb_int_range' */
                ret = netsnmp_check_vb_int( request->requestvb );
                if ( ret != SNMP_ERR_NOERROR ) {
                    netsnmp_set_request_error( reqinfo, request, ret );
                    return SNMP_ERR_NOERROR;
                }
                break;
            default:
                netsnmp_set_request_error( reqinfo, request,
                                           SNMP_ERR_NOTWRITABLE );
                return SNMP_ERR_NOERROR;
            }
        }
        break;

    case MODE_SET_RESERVE2:
        break;

    case MODE_SET_FREE:
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     ieee8021QBridgePortVlanTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021QBRIDGEPVID:
                table_entry->old_ieee8021QBridgePvid = table_entry->ieee8021QBridgePvid;
                table_entry->ieee8021QBridgePvid     = *request->requestvb->val.integer;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTACCEPTABLEFRAMETYPES:
                table_entry->old_ieee8021QBridgePortAcceptableFrameTypes = table_entry->ieee8021QBridgePortAcceptableFrameTypes;
                table_entry->ieee8021QBridgePortAcceptableFrameTypes     = *request->requestvb->val.integer;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTINGRESSFILTERING:
                table_entry->old_ieee8021QBridgePortIngressFiltering = table_entry->ieee8021QBridgePortIngressFiltering;
                table_entry->ieee8021QBridgePortIngressFiltering     = *request->requestvb->val.integer;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPENABLEDSTATUS:
                table_entry->old_ieee8021QBridgePortMvrpEnabledStatus = table_entry->ieee8021QBridgePortMvrpEnabledStatus;
                table_entry->ieee8021QBridgePortMvrpEnabledStatus     = *request->requestvb->val.integer;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTRESTRICTEDVLANREGISTRATION:
                table_entry->old_ieee8021QBridgePortRestrictedVlanRegistration = table_entry->ieee8021QBridgePortRestrictedVlanRegistration;
                table_entry->ieee8021QBridgePortRestrictedVlanRegistration     = *request->requestvb->val.integer;
                break;
            }
        }
        break;

    case MODE_SET_UNDO:
        for (request=requests; request; request=request->next) {
            table_info  =     netsnmp_extract_table_info( request);
            table_entry =     ieee8021QBridgePortVlanTable_get_entry( table_info->indexes );
    
            switch (table_info->colnum) {
            case COLUMN_IEEE8021QBRIDGEPVID:
                table_entry->ieee8021QBridgePvid     = table_entry->old_ieee8021QBridgePvid;
                table_entry->old_ieee8021QBridgePvid = 0;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTACCEPTABLEFRAMETYPES:
                table_entry->ieee8021QBridgePortAcceptableFrameTypes     = table_entry->old_ieee8021QBridgePortAcceptableFrameTypes;
                table_entry->old_ieee8021QBridgePortAcceptableFrameTypes = 0;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTINGRESSFILTERING:
                table_entry->ieee8021QBridgePortIngressFiltering     = table_entry->old_ieee8021QBridgePortIngressFiltering;
                table_entry->old_ieee8021QBridgePortIngressFiltering = 0;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTMVRPENABLEDSTATUS:
                table_entry->ieee8021QBridgePortMvrpEnabledStatus     = table_entry->old_ieee8021QBridgePortMvrpEnabledStatus;
                table_entry->old_ieee8021QBridgePortMvrpEnabledStatus = 0;
                break;
            case COLUMN_IEEE8021QBRIDGEPORTRESTRICTEDVLANREGISTRATION:
                table_entry->ieee8021QBridgePortRestrictedVlanRegistration     = table_entry->old_ieee8021QBridgePortRestrictedVlanRegistration;
                table_entry->old_ieee8021QBridgePortRestrictedVlanRegistration = 0;
                break;
            }
        }
        break;

    case MODE_SET_COMMIT:
        break;
    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the ieee8021QBridgePortVlanTable table by defining its contents and how it's structured */
static void
initialize_table_ieee8021QBridgePortVlanTable(void)
{
    const oid ieee8021QBridgePortVlanTable_oid[] = {1,3,111,2,802,1,1,4,1,4,5};
    netsnmp_handler_registration    *reg;
    netsnmp_table_registration_info *table_info;

    reg = netsnmp_create_handler_registration(
              "ieee8021QBridgePortVlanTable",     ieee8021QBridgePortVlanTable_handler,
              ieee8021QBridgePortVlanTable_oid, OID_LENGTH(ieee8021QBridgePortVlanTable_oid),
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_UNSIGNED,  /* index: ieee8021BridgeBasePortComponentId */
                           ASN_UNSIGNED,  /* index: ieee8021BridgeBasePort */
                           0);

    table_info->min_column = COLUMN_IEEE8021QBRIDGEPVID;
    table_info->max_column = COLUMN_IEEE8021QBRIDGEPORTRESTRICTEDVLANREGISTRATION;

    netsnmp_register_table( reg, table_info );

    /* Initialise the contents of the table here */
}

/** Initializes the ieee8021QBridgePortVlanTable module */
void
init_ieee8021QBridgePortVlanTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_ieee8021QBridgePortVlanTable();
}
