/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */
#ifndef IEEE8021QBRIDGEVLANSTATICTABLE_H
#define IEEE8021QBRIDGEVLANSTATICTABLE_H

void init_ieee8021QBridgeVlanStaticTable(void);

#endif /* IEEE8021QBRIDGEVLANSTATICTABLE_H */
