/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 12088 $ of $
 *
 * $Id:$
 *
 * @file ieee8021BridgeBaseTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef IEEE8021BRIDGEBASETABLE_DATA_GET_H
#define IEEE8021BRIDGEBASETABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ieee8021BridgeBaseTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IEEE8021-BRIDGE-MIB::ieee8021BridgeBaseTable is subid 1 of ieee8021BridgeBase.
 * Its status is Current.
 * OID: .1.3.111.2.802.1.1.2.1.1.1, length: 11
*/
    /*
     * indexes
     */

    int ieee8021BridgeBaseBridgeAddress_get( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, char **ieee8021BridgeBaseBridgeAddress_val_ptr_ptr, size_t *ieee8021BridgeBaseBridgeAddress_val_ptr_len_ptr );
    int ieee8021BridgeBaseNumPorts_get( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, long * ieee8021BridgeBaseNumPorts_val_ptr );
    int ieee8021BridgeBaseComponentType_get( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, u_long * ieee8021BridgeBaseComponentType_val_ptr );
    int ieee8021BridgeBaseDeviceCapabilities_get( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, u_long * ieee8021BridgeBaseDeviceCapabilities_val_ptr );
    int ieee8021BridgeBaseTrafficClassesEnabled_get( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, u_long * ieee8021BridgeBaseTrafficClassesEnabled_val_ptr );
    int ieee8021BridgeBaseMmrpEnabledStatus_get( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, u_long * ieee8021BridgeBaseMmrpEnabledStatus_val_ptr );
    int ieee8021BridgeBaseRowStatus_get( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, u_long * ieee8021BridgeBaseRowStatus_val_ptr );


int ieee8021BridgeBaseTable_indexes_set_tbl_idx(ieee8021BridgeBaseTable_mib_index *tbl_idx, u_long ieee8021BridgeBaseComponentId_val);
int ieee8021BridgeBaseTable_indexes_set(ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx, u_long ieee8021BridgeBaseComponentId_val);




#ifdef __cplusplus
}
#endif

#endif /* IEEE8021BRIDGEBASETABLE_DATA_GET_H */
/** @} */
