/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $ 
 *
 * $Id:$
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "ieee8021BridgeBaseTable.h"


#include "ieee8021BridgeBaseTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ieee8021BridgeBaseTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IEEE8021-BRIDGE-MIB::ieee8021BridgeBaseTable is subid 1 of ieee8021BridgeBase.
 * Its status is Current.
 * OID: .1.3.111.2.802.1.1.2.1.1.1, length: 11
*/

/**
 * initialization for ieee8021BridgeBaseTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param ieee8021BridgeBaseTable_reg
 *        Pointer to ieee8021BridgeBaseTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
ieee8021BridgeBaseTable_init_data(ieee8021BridgeBaseTable_registration * ieee8021BridgeBaseTable_reg)
{
    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize ieee8021BridgeBaseTable data.
     */

    return MFD_SUCCESS;
} /* ieee8021BridgeBaseTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
ieee8021BridgeBaseTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_container_init","called\n"));
    
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,"bad container param to ieee8021BridgeBaseTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,"bad cache param to ieee8021BridgeBaseTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up ieee8021BridgeBaseTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = IEEE8021BRIDGEBASETABLE_CACHE_TIMEOUT; /* seconds */
} /* ieee8021BridgeBaseTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before ieee8021BridgeBaseTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
ieee8021BridgeBaseTable_container_shutdown(netsnmp_container *container_ptr)
{
    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_container_shutdown","called\n"));
    
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,"bad params to ieee8021BridgeBaseTable_container_shutdown\n");
        return;
    }

} /* ieee8021BridgeBaseTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement ieee8021BridgeBaseTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  ieee8021BridgeBaseTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
ieee8021BridgeBaseTable_container_load(netsnmp_container *container)
{
    ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx;
    size_t                 count = 0;

    /*
     * temporary storage for index values
     */
        /*
         * ieee8021BridgeBaseComponentId(1)/IEEE8021PbbComponentIdentifier/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H
         */
   u_long   ieee8021BridgeBaseComponentId;


    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_container_load","called\n"));

    /*
     * TODO:351:M: |-> Load/update data in the ieee8021BridgeBaseTable container.
     * loop over your ieee8021BridgeBaseTable data, allocate a rowreq context,
     * set the index(es) [and data, optionally] and insert into
     * the container.
     */
    while( 1 ) {
        /*
         * check for end of data; bail out if there is no more data
         */
        if( 1 )
            break;

        /*
         * TODO:352:M: |   |-> set indexes in new ieee8021BridgeBaseTable rowreq context.
         * data context will be set from the param (unless NULL,
         *      in which case a new data context will be allocated)
         */
        rowreq_ctx = ieee8021BridgeBaseTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if(MFD_SUCCESS != ieee8021BridgeBaseTable_indexes_set(rowreq_ctx
                               , ieee8021BridgeBaseComponentId
               )) {
            snmp_log(LOG_ERR,"error setting index while loading "
                     "ieee8021BridgeBaseTable data.\n");
            ieee8021BridgeBaseTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }

        /*
         * TODO:352:r: |   |-> populate ieee8021BridgeBaseTable data context.
         * Populate data context here. (optionally, delay until row prep)
         */
    /*
     * TRANSIENT or semi-TRANSIENT data:
     * copy data or save any info needed to do it in row_prep.
     */
    /*
     * setup/save data for ieee8021BridgeBaseBridgeAddress
     * ieee8021BridgeBaseBridgeAddress(2)/MacAddress/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H
     */
    /** no mapping */
    /*
     * make sure there is enough space for ieee8021BridgeBaseBridgeAddress data
     */
    if ((NULL == rowreq_ctx->data.ieee8021BridgeBaseBridgeAddress) ||
        (rowreq_ctx->data.ieee8021BridgeBaseBridgeAddress_len <
         (ieee8021BridgeBaseBridgeAddress_len* sizeof(ieee8021BridgeBaseBridgeAddress[0])))) {
        snmp_log(LOG_ERR,"not enough space for value\n");
        return MFD_ERROR;
    }
    rowreq_ctx->data.ieee8021BridgeBaseBridgeAddress_len = ieee8021BridgeBaseBridgeAddress_len* sizeof(ieee8021BridgeBaseBridgeAddress[0]);
    memcpy( rowreq_ctx->data.ieee8021BridgeBaseBridgeAddress, ieee8021BridgeBaseBridgeAddress, ieee8021BridgeBaseBridgeAddress_len* sizeof(ieee8021BridgeBaseBridgeAddress[0]) );
    
    /*
     * setup/save data for ieee8021BridgeBaseNumPorts
     * ieee8021BridgeBaseNumPorts(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
     */
    /** no mapping */
    rowreq_ctx->data.ieee8021BridgeBaseNumPorts = ieee8021BridgeBaseNumPorts;
    
    /*
     * setup/save data for ieee8021BridgeBaseComponentType
     * ieee8021BridgeBaseComponentType(4)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
     */
    /** no mapping */
    rowreq_ctx->data.ieee8021BridgeBaseComponentType = ieee8021BridgeBaseComponentType;
    
    /*
     * setup/save data for ieee8021BridgeBaseDeviceCapabilities
     * ieee8021BridgeBaseDeviceCapabilities(5)/BITS/ASN_OCTET_STR/char(u_long)//L/A/W/E/r/d/h
     */
    /** no mapping */
    rowreq_ctx->data.ieee8021BridgeBaseDeviceCapabilities = ieee8021BridgeBaseDeviceCapabilities;
    
    /*
     * setup/save data for ieee8021BridgeBaseTrafficClassesEnabled
     * ieee8021BridgeBaseTrafficClassesEnabled(6)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
     */
    /** no mapping */
    rowreq_ctx->data.ieee8021BridgeBaseTrafficClassesEnabled = ieee8021BridgeBaseTrafficClassesEnabled;
    
    /*
     * setup/save data for ieee8021BridgeBaseMmrpEnabledStatus
     * ieee8021BridgeBaseMmrpEnabledStatus(7)/TruthValue/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h
     */
    /** no mapping */
    rowreq_ctx->data.ieee8021BridgeBaseMmrpEnabledStatus = ieee8021BridgeBaseMmrpEnabledStatus;
    
    /*
     * setup/save data for ieee8021BridgeBaseRowStatus
     * ieee8021BridgeBaseRowStatus(8)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h
     */
    /** no mapping */
    rowreq_ctx->data.ieee8021BridgeBaseRowStatus = ieee8021BridgeBaseRowStatus;
    
        
        /*
         * insert into table container
         */
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }

    DEBUGMSGT(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_container_load",
               "inserted %d records\n", count));

    return MFD_SUCCESS;
} /* ieee8021BridgeBaseTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
ieee8021BridgeBaseTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_container_free","called\n"));

    /*
     * TODO:380:M: Free ieee8021BridgeBaseTable container data.
     */
} /* ieee8021BridgeBaseTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
ieee8021BridgeBaseTable_row_prep( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* ieee8021BridgeBaseTable_row_prep */

/*
 * TODO:420:r: Implement ieee8021BridgeBaseTable index validation.
 */
/*---------------------------------------------------------------------
 * IEEE8021-BRIDGE-MIB::ieee8021BridgeBaseEntry.ieee8021BridgeBaseComponentId
 * ieee8021BridgeBaseComponentId is subid 1 of ieee8021BridgeBaseEntry.
 * Its status is Current, and its access level is NoAccess.
 * OID: .1.3.111.2.802.1.1.2.1.1.1.1.1
 * Description:
The component identifier is used to distinguish between the
        multiple virtual bridge instances within a PBB.  In simple
        situations where there is only a single component the default
        value is 1.
 *
 * Attributes:
 *   accessible 0     isscalar 0     enums  0      hasdefval 0
 *   readable   0     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: d
 *
 * Ranges:  1 - 2147483647;
 *
 * Its syntax is IEEE8021PbbComponentIdentifier (based on perltype UNSIGNED32)
 * The net-snmp type is ASN_UNSIGNED. The C type decl is u_long (u_long)
 *
 *
 *
 * NOTE: NODE ieee8021BridgeBaseComponentId IS NOT ACCESSIBLE
 *
 *
 */
/**
 * check validity of ieee8021BridgeBaseComponentId index portion
 *
 * @retval MFD_SUCCESS   : the incoming value is legal
 * @retval MFD_ERROR     : the incoming value is NOT legal
 *
 * @note this is not the place to do any checks for the sanity
 *       of multiple indexes. Those types of checks should be done in the
 *       ieee8021BridgeBaseTable_validate_index() function.
 *
 * @note Also keep in mind that if the index refers to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 * The following checks have already been done for you:
 *    The value is in (one of) the range set(s):  1 - 2147483647
 *
 * If there a no other checks you need to do, simply return MFD_SUCCESS.
 */
int
ieee8021BridgeBaseComponentId_check_index( ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx )
{
    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseComponentId_check_index","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:426:M: |-> Check ieee8021BridgeBaseTable index ieee8021BridgeBaseComponentId.
     * check that index value in the table context is legal.
     * (rowreq_ctx->tbl_index.ieee8021BridgeBaseComponentId)
     */

    return MFD_SUCCESS; /* ieee8021BridgeBaseComponentId index ok */
} /* ieee8021BridgeBaseComponentId_check_index */

/**
 * verify specified index is valid.
 *
 * This check is independent of whether or not the values specified for
 * the columns of the new row are valid. Column values and row consistency
 * will be checked later. At this point, only the index values should be
 * checked.
 *
 * All of the individual index validation functions have been called, so this
 * is the place to make sure they are valid as a whole when combined. If
 * you only have one index, then you probably don't need to do anything else
 * here.
 * 
 * @note Keep in mind that if the indexes refer to a row in this or
 *       some other table, you can't check for that row here to make
 *       decisions, since that row might not be created yet, but may
 *       be created during the processing this request. If you have
 *       such checks, they should be done in the check_dependencies
 *       function, because any new/deleted/changed rows should be
 *       available then.
 *
 *
 * @param ieee8021BridgeBaseTable_reg
 *        Pointer to the user registration data
 * @param ieee8021BridgeBaseTable_rowreq_ctx
 *        Pointer to the users context.
 * @retval MFD_SUCCESS            : success
 * @retval MFD_CANNOT_CREATE_NOW  : index not valid right now
 * @retval MFD_CANNOT_CREATE_EVER : index never valid
 */
int
ieee8021BridgeBaseTable_validate_index( ieee8021BridgeBaseTable_registration * ieee8021BridgeBaseTable_reg,
                           ieee8021BridgeBaseTable_rowreq_ctx *rowreq_ctx)
{
    int rc = MFD_SUCCESS;

    DEBUGMSGTL(("verbose:ieee8021BridgeBaseTable:ieee8021BridgeBaseTable_validate_index","called\n"));

    /** we should have a non-NULL pointer */
    netsnmp_assert( NULL != rowreq_ctx );

    /*
     * TODO:430:M: |-> Validate potential ieee8021BridgeBaseTable index.
     */
    if(1) {
        snmp_log(LOG_WARNING,"invalid index for a new row in the "
                 "ieee8021BridgeBaseTable table.\n");
        /*
         * determine failure type.
         *
         * If the index could not ever be created, return MFD_NOT_EVER
         * If the index can not be created under the present circumstances
         * (even though it could be created under other circumstances),
         * return MFD_NOT_NOW.
         */
        if(0) {
            return MFD_CANNOT_CREATE_EVER;
        }
        else {
            return MFD_CANNOT_CREATE_NOW;
        }
    }

    return rc;
} /* ieee8021BridgeBaseTable_validate_index */

/** @} */
