ROOTFS_OVERRIDE = $(WRS_BASE_DIR)/../userspace/rootfs_override

OBJS = rtu_fd_proxy.o endpoint_hw.o

CC   = $(CROSS_COMPILE)gcc

# We must include stuff from various headers, which are installed.
# If this is build under build scripts, it's $WRS_OUTPUT_DIR/images/wr
WR_INSTALL_ROOT ?= /usr/lib/white-rabbit
WR_INCLUDE = $(WR_INSTALL_ROOT)/include
WR_LIB = $(WR_INSTALL_ROOT)/lib

CFLAGS := -fPIC -shared -O2 -DDEBUG -Wall -ggdb -DTRACE_ALL -I../wrsw_hal \
         -I. -I../include -I../libwripc -I$(WR_INCLUDE) -I$(LINUX)/include \
         -I$(WRS_OUTPUT_DIR)/build/ptp-noposix/libwripc

# -I$(CROSS_COMPILE_ARM_PATH)/../include

LDFLAGS := -fPIC -shared -L. -L$(WR_LIB) -L../libwripc \
           -lwripc -lminipc

RM := rm -f

LIB  = libwrrtu.so

all: $(LIB)

$(LIB): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

clean:
	$(RM) $(LIB) $(OBJS)

install: all
	install -d $(WR_INSTALL_ROOT)/lib
	install $(LIB) $(WR_INSTALL_ROOT)/lib
	#install libminipc.so $(ROOTFS_OVERRIDE)/usr/lib
	#install libwripc.so $(ROOTFS_OVERRIDE)/usr/lib
