<?php

session_start();
ob_start();

include_once "data/wrs-info.php";

if (empty($_SESSION["WRS_INFO"])){
	$_SESSION["WRS_INFO"] = $GLOBALS["WRS_INFO"];
}

// Forms are firstly generated by default, but can be modified by users.

$WRS_TABLE_INFO = Array (
	DASHBOARD => Array(
		DASHBOARD_00 => Array(
			name => HOSTNAME,
			value => $_SESSION["WRS_INFO"][HOSTNAME],
		),
		DASHBOARD_02 => Array(
			name => "IP Address",
			value => $_SESSION["WRS_INFO"][IPADDRESS],
		),
		DASHBOARD_03 => Array(
			name => MACADDRESS,
			value => $_SESSION["WRS_INFO"][MACADDRESS],
		),
		DASHBOARD_04 => Array(
			name => KERNEL,
			value => $_SESSION["WRS_INFO"][KERNEL],
		),
		DASHBOARD_05 => Array(
			name => FIRMWARE,
			value => $_SESSION["WRS_INFO"][FIRMWARE],
		),
		DASHBOARD_06 => Array(
			name => HARDWARE,
			value => $_SESSION["WRS_INFO"][HARDWARE],
		),
		DASHBOARD_07 => Array(
			name => FPGA,
			value => $_SESSION["WRS_INFO"][FPGA],
		),
		DASHBOARD_08 => Array(
			name => MANUFACTURER,
			value => $_SESSION["WRS_INFO"][MANUFACTURER],
		),
		DASHBOARD_09 => Array(
			name => SERIALNUMBER,
			value => $_SESSION["WRS_INFO"][SERIALNUMBER],
		),
		DASHBOARD_10 => Array(
			name => KERNELCOMPILEDDATE,
			value => $_SESSION["WRS_INFO"][KERNELCOMPILEDDATE],
		),
	),
	CONTACT => Array (
		CONTACT_00 => Array(
			name => FIRMWARE,
			value => $_SESSION["WRS_INFO"][FIRMWARE],
		),
		CONTACT_01 => Array(
			name => KERNEL,
			value => $_SESSION["WRS_INFO"][KERNEL],
		),
		CONTACT_02 => Array(
			name => COMPILEDBY,
			value => $_SESSION["WRS_INFO"][COMPILEDBY],
		),
		CONTACT_03 => Array( 
			name => KERNELCOMPILEDDATE,
			value => $_SESSION["WRS_INFO"][KERNELCOMPILEDDATE],
		),
		CONTACT_04 => Array( 
			name => HARDWARE,
			value => $_SESSION["WRS_INFO"][HARDWARE],
		),	
		CONTACT_05 => Array( 
			name => FPGA,
			value => $_SESSION["WRS_INFO"][FPGA],
		),	
		CONTACT_06 => Array( 
			name => MANUFACTURER,
			value => $_SESSION["WRS_INFO"][MANUFACTURER],
		),		
		CONTACT_07 => Array( 
			name => SERIALNUMBER,
			value => $_SESSION["WRS_INFO"][SERIALNUMBER],
		),	
		CONTACT_08 => Array( 
			name => GATEWARE,
			value => $_SESSION["WRS_INFO"][GATEWARE],
		),	
		CONTACT_09 => Array( 
			name => GATEWAREBUILD,
			value => $_SESSION["WRS_INFO"][GATEWAREBUILD],
		),	
		CONTACT_10 => Array( 
			name => WRSHDLCOMMIT,
			value => $_SESSION["WRS_INFO"][WRSHDLCOMMIT],
		),	
		CONTACT_11 => Array( 
			name => GCORESCOMMIT,
			value => $_SESSION["WRS_INFO"][GCORESCOMMIT],
		),	
		CONTACT_12 => Array( 
			name => WRCORESCOMMIT,
			value => $_SESSION["WRS_INFO"][WRCORESCOMMIT],
		),	
	),
	NETWORK_SETUP => Array(
		NETWORK_SETUP_00 => Array(
			name => IPADDRESS,
			value => $_SESSION["WRS_INFO"][IPADDRESS],
		),
		NETWORK_SETUP_01 => Array(
			name => NETMASK,
			value => $_SESSION["WRS_INFO"][NETMASK],
		),
		NETWORK_SETUP_02 => Array(
			name => BROADCAST,
			value => $_SESSION["WRS_INFO"][BROADCAST],
		),
		NETWORK_SETUP_03 => Array(
			name => MACADDRESS,
			value => $_SESSION["WRS_INFO"][MACADDRESS],
		),
	),
);

	
$WRS_FORMS = Array(
	
	NETWORK_SETUP => Array(
		NETWORK_SETUP_00 => Array(
			name => "IP Address",
			value => "192.168.1.53",
			vname => "ip",
		),
		NETWORK_SETUP_01 => Array(
			name => "Netmask",
			value => "255.255.255.0",
			vname => "netmask",
		),
		NETWORK_SETUP_02 => Array(
			name => "Broadcast",
			value => "192.168.1.255",
			vname => "broadcast",
		),
		NETWORK_SETUP_03 => Array(
			name => "Network",
			value => "192.168.1.0",
			vname => "network",
		),
		NETWORK_SETUP_04 => Array(
			name => "Gateway",
			value => "192.168.1.1",
			vname => "gateway",
		),	
	),
	
	CONFIG_PPSI => Array(
		CONFIG_PPSI_00 => Array(
			name => "Clock Class",
			value => "",
			vname => "clkclass",
		),
		CONFIG_PPSI_01 => Array(
			name => "Clock Accuracy",
			value => "",
			vname => "clkacc",
		),
	),

);

?>




