/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef IEEE8021BRIDGEPORTPRIORITYTABLE_DATA_ACCESS_H
#define IEEE8021BRIDGEPORTPRIORITYTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ieee8021BridgePortPriorityTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IEEE8021-BRIDGE-MIB::ieee8021BridgePortPriorityTable is subid 1 of ieee8021BridgePriority.
 * Its status is Current.
 * OID: .1.3.111.2.802.1.1.2.1.3.1, length: 11
*/


    int ieee8021BridgePortPriorityTable_init_data(ieee8021BridgePortPriorityTable_registration * ieee8021BridgePortPriorityTable_reg);


    /*
     * TODO:180:o: Review ieee8021BridgePortPriorityTable cache timeout.
     * The number of seconds before the cache times out
     */
#define IEEE8021BRIDGEPORTPRIORITYTABLE_CACHE_TIMEOUT   60

void ieee8021BridgePortPriorityTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void ieee8021BridgePortPriorityTable_container_shutdown(netsnmp_container *container_ptr);

int ieee8021BridgePortPriorityTable_container_load(netsnmp_container *container);
void ieee8021BridgePortPriorityTable_container_free(netsnmp_container *container);

int ieee8021BridgePortPriorityTable_cache_load(netsnmp_container *container);
void ieee8021BridgePortPriorityTable_cache_free(netsnmp_container *container);

    int ieee8021BridgePortPriorityTable_row_prep( ieee8021BridgePortPriorityTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* IEEE8021BRIDGEPORTPRIORITYTABLE_DATA_ACCESS_H */
