/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 14170 $ of $
 *
 * $Id:$
 */
#ifndef IEEE8021BRIDGETPPORTTABLE_DATA_ACCESS_H
#define IEEE8021BRIDGETPPORTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ieee8021BridgeTpPortTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IEEE8021-BRIDGE-MIB::ieee8021BridgeTpPortTable is subid 1 of ieee8021BridgeTp.
 * Its status is Current.
 * OID: .1.3.111.2.802.1.1.2.1.2.1, length: 11
*/


    int ieee8021BridgeTpPortTable_init_data(ieee8021BridgeTpPortTable_registration * ieee8021BridgeTpPortTable_reg);


    /*
     * TODO:180:o: Review ieee8021BridgeTpPortTable cache timeout.
     * The number of seconds before the cache times out
     */
#define IEEE8021BRIDGETPPORTTABLE_CACHE_TIMEOUT   60

void ieee8021BridgeTpPortTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void ieee8021BridgeTpPortTable_container_shutdown(netsnmp_container *container_ptr);

int ieee8021BridgeTpPortTable_container_load(netsnmp_container *container);
void ieee8021BridgeTpPortTable_container_free(netsnmp_container *container);

int ieee8021BridgeTpPortTable_cache_load(netsnmp_container *container);
void ieee8021BridgeTpPortTable_cache_free(netsnmp_container *container);

    int ieee8021BridgeTpPortTable_row_prep( ieee8021BridgeTpPortTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* IEEE8021BRIDGETPPORTTABLE_DATA_ACCESS_H */
