#!/bin/sh
if [ -n "$WRS_VERBOSE" ]; then
    set -x;
    SH_X="sh -x"
fi

# Stop all init scripts in /etc/init.d
# executing them in numerical order.
#

for i in /etc/rcS/K??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set stop
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    eval $SH_X $i stop
	    ;;
    esac
done

