#!/bin/sh
#
# Start the network....
#

#MAC=`/wr/bin/get_board_mac`
#echo "Management port MAC address: $MAC"
#ifconfig eth0 hw ether $MAC
#ifplugd -i eth0
#udhcpc -n

rootloc=`mount | grep rootfs | grep nfs`
if [ "$rootloc" != "" ]; then
	echo "Running via NFS, no ifplugd."
else
	echo "Starting ifplugd..."
	/usr/sbin/ifplugd -I -f -i eth0
fi
