#!/bin/sh
#
# Starts snmpd.
#

# Make sure the dropbearkey progam exists
[ -f /wr/bin/wrsw_hal ] || exit 0

start() {
 	echo "Starting WR SNMP agent: "
	export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/wr/lib"
    /usr/sbin/snmpd -D8021Q -Lf /var/log/snmpd.log
    #/usr/sbin/snmpd -Ln
}
stop() {
	killall snmpd
}

restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
