#!/bin/sh

# Copyright CERN, 2012
# Author: Juan Luis Manas <juan.manas@integrasys.es>
# Licence: GPL v2 or later.

# Basic Filtering Service
# Description: Create dynamic filtering entry that conflicts with static info.
# Goal: Verify that the RTU does not learn ny dynamic information when
# there is a previous static entry for a given MAC address.

echo
echo "---------------------------------------------------------------------"
echo "BFS-6. Create dynamic filtering entry that conflicts with static info"
echo "---------------------------------------------------------------------"

# 1. A static filtering entry is created by management for unicast MAC address
# 22:00:10:00:06:06 (34.0.16.0.6.6 dec) specifying forward on port DP0.
MAC=22:0:10:0:6:6
MAC_DEC=34.0.16.0.6.6

echo "# Create static filtering entry: mac=$MAC port=DP0"
snmpset $SNMPSET_FLAGS \
    ieee8021QBridgeStaticUnicastRowStatus.1.$VLAN.$MAC_DEC.0                \
        i $RS_CREATEANDGO                                                   \
    ieee8021QBridgeStaticUnicastStaticEgressPorts.1.$VLAN.$MAC_DEC.0        \
        x 0000010000000000000000000000000000000000000000000000000000000000  \
    ieee8021QBridgeStaticUnicastForbiddenEgressPorts.1.$VLAN.$MAC_DEC.0     \
        x 0101000101010101010101010101010101010101010101010101010101010101  \
    ieee8021QBridgeStaticUnicastStorageType.1.$VLAN.$MAC_DEC.0              \
        i 2                                                                 \
    > /dev/null 2>&1

echo "# Find static filtering entry: mac=$MAC"
snmptable $SNMPTAB_FLAGS \
    IEEE8021-Q-BRIDGE-MIB:ieee8021QBridgeStaticUnicastTable | grep -i -w $MAC

# 2. A frame with source MAC address 22:00:10:00:06:06 is sent from port
# eth1 at the test station (dynamically learned?)
# 3. A frame with destination MAC address 22:00:10:00:06:06 is sent from port
# eth0 at the test station. (verifies whether static of dynamic info is used)
swflood ./cfg/bfs-6.cfg > /dev/null 2>&1
