
all:
	$(MAKE) -C config all
	$(MAKE) -C ieee8021bridge all
	$(MAKE) -C ieee8021QBridge all


clean:
	$(MAKE) -C config clean
	$(MAKE) -C ieee8021bridge clean
	$(MAKE) -C ieee8021QBridge clean


install:
	$(MAKE) -C config install
	$(MAKE) -C ieee8021bridge install
	$(MAKE) -C ieee8021QBridge install
