
all:
	$(MAKE) -C config all
	$(MAKE) -C ieee8021bridge all


clean:
	$(MAKE) -C config clean
	$(MAKE) -C ieee8021bridge clean


install:
	$(MAKE) -C config install
	$(MAKE) -C ieee8021bridge install
