/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */
#ifndef PSTATSTABLE_H
#define PSTATSTABLE_H

void            init_pstatsTable(void);

#endif                          /* PSTATSTABLE_H */
