/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.raw-table.conf 17436 2009-03-31 15:12:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "pstatsTable.h"


/*
 * column number definitions for table pstatsTable 
 */
#define COLUMN_PSTATSINDEX		1
#define COLUMN_PSTATSDESCR		2
#define COLUMN_PSTATSWR0		3
#define COLUMN_PSTATSWR1		4
#define COLUMN_PSTATSWR2		5
#define COLUMN_PSTATSWR3		6
#define COLUMN_PSTATSWR4		7
#define COLUMN_PSTATSWR5		8
#define COLUMN_PSTATSWR6		9
#define COLUMN_PSTATSWR7		10
#define COLUMN_PSTATSWR8		11
#define COLUMN_PSTATSWR9		12
#define COLUMN_PSTATSWR10		13
#define COLUMN_PSTATSWR11		14
#define COLUMN_PSTATSWR12		15
#define COLUMN_PSTATSWR13		16
#define COLUMN_PSTATSWR14		17
#define COLUMN_PSTATSWR15		18
#define COLUMN_PSTATSWR16		19
#define COLUMN_PSTATSWR17		20

    /*
     * Typical data structure for a row entry 
     */
struct pstatsTable_entry {
    /*
     * Index values 
     */
    long            pstatsIndex;

    /*
     * Column values 
     */
    char            pstatsDescr[32];
    size_t          pstatsDescr_len;
    u_long          pstatsWR0;
    u_long          pstatsWR1;
    u_long          pstatsWR2;
    u_long          pstatsWR3;
    u_long          pstatsWR4;
    u_long          pstatsWR5;
    u_long          pstatsWR6;
    u_long          pstatsWR7;
    u_long          pstatsWR8;
    u_long          pstatsWR9;
    u_long          pstatsWR10;
    u_long          pstatsWR11;
    u_long          pstatsWR12;
    u_long          pstatsWR13;
    u_long          pstatsWR14;
    u_long          pstatsWR15;
    u_long          pstatsWR16;
    u_long          pstatsWR17;

    int             valid;
};

#include <stdarg.h>
static FILE *logf;

static int logmsg(const char *fmt, ...)
{
        va_list args;
        int ret;

	if (WRS_WITH_SNMP_HACKISH_LOG) {
		if (!logf)
			logf = fopen("/dev/console", "w");

		va_start(args, fmt);
		ret = vfprintf(logf, fmt, args);
		va_end(args);

		return ret;
	} else {
		return 0;
	}
}

int dumpstruct(FILE *dest, char *name, void *ptr, int size)
{
    int ret = 0, i;
    unsigned char *p = ptr;

	if (WRS_WITH_SNMP_HACKISH_LOG) {
		ret = fprintf(dest, "dump %s at %p (size 0x%x)\n",
			      name, ptr, size);
		for (i = 0; i < size; ) {
			ret += fprintf(dest, "%02x", p[i]);
			i++;
			ret += fprintf(dest, i & 3 ? " " : i & 0xf ? "  " : "\n");
		}
		if (i & 0xf)
			ret += fprintf(dest, "\n");
	}
	return ret;
}

/*
 * create a new row in the table 
 */
static struct pstatsTable_entry *
pstatsTable_createEntry(int dummy, long pstatsIndex)
{
    struct pstatsTable_entry *entry;

    logmsg("%s: %i\n", __func__, __LINE__);
    entry = SNMP_MALLOC_TYPEDEF(struct pstatsTable_entry);
    if (!entry)
        return NULL;

    /*
     * XXX - insert entry into local data structure 
     */
    return entry;
}

/*
 * remove a row from the table 
 */
static void
pstatsTable_removeEntry(struct pstatsTable_entry *entry)
{
    logmsg("%s: %i\n", __func__, __LINE__);
    if (!entry)
        return;                 /* Nothing to remove */
    logmsg("%s: %i\n", __func__, __LINE__);

    /*
     * XXX - remove entry from local data structure 
     */

    if (entry)
        SNMP_FREE(entry);       /* XXX - release any other internal resources */
}


/** determine the appropriate row for an exact request */
static struct pstatsTable_entry *
pstatsTable_get_entry(netsnmp_variable_list * indexes)
{
    struct pstatsTable_entry *row = NULL;

    logmsg("%s: %i\n", __func__, __LINE__);
    /*
     * XXX - Use the 'indexes' parameter to retrieve the data
     * structure for the requested row, and return this. 
     */
    return row;
}

/** determine the appropriate row for an fuzzy request */
static struct pstatsTable_entry *
pstatsTable_get_next_entry(netsnmp_handler_registration *reginfo,
                           netsnmp_request_info *request,
                           int column, netsnmp_variable_list * indexes)
{
    struct pstatsTable_entry *row = NULL;
    oid             build_space[MAX_OID_LEN];
    size_t          build_space_len = 0;
    size_t          index_oid_len = 0;

    logmsg("%s: %i\n", __func__, __LINE__);
    /*
     * XXX - Use the 'indexes' parameter to identify the
     * next row in the table.... 
     */
    {
	    int i;
	    dumpstruct(logf, "variable_list", indexes, sizeof(*indexes));
	    logmsg("indexes: \n");
	    for (i = 0; i < indexes->name_length; i++)
		    logmsg(".%i", (int)indexes->name[i]);
    }

    /*
     * XXX   .... update the 'indexes' parameter with the
     * appropriate index values ... 
     */

    /*
     * ... and update the requested OID to match this instance 
     */
    memcpy(build_space, reginfo->rootoid,       /* registered oid */
           reginfo->rootoid_len * sizeof(oid));
    build_space_len = reginfo->rootoid_len;
    build_space[build_space_len++] = 1; /* entry */
    build_space[build_space_len++] = column;    /* column */
    build_oid_noalloc(build_space + build_space_len,
                      MAX_OID_LEN - build_space_len, &index_oid_len,
                      NULL, 0, indexes);
    snmp_set_var_objid(request->requestvb, build_space,
                       build_space_len + index_oid_len);

    /*
     * Finally, return the data structure for this row 
     */
    return row;
}


/** handles requests for the pstatsTable table */
static int
pstatsTable_handler(netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info *reqinfo,
                    netsnmp_request_info *requests)
{

    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    struct pstatsTable_entry *table_entry;

    logmsg("%s: mode %i\n", __func__, reqinfo->mode);
    switch (reqinfo->mode) {
        /*
         * Read-support
         */
    case MODE_GET:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
            table_entry = pstatsTable_get_entry(table_info->indexes);

	    logmsg("%s: colnum %i\n", __func__, table_info->colnum);
            switch (table_info->colnum) {
            case COLUMN_PSTATSINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->pstatsIndex);
                break;
            case COLUMN_PSTATSDESCR:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->pstatsDescr,
                                         table_entry->pstatsDescr_len);
                break;
            case COLUMN_PSTATSWR0:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR0);
                break;
            case COLUMN_PSTATSWR1:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR1);
                break;
            case COLUMN_PSTATSWR2:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR2);
                break;
            case COLUMN_PSTATSWR3:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR3);
                break;
            case COLUMN_PSTATSWR4:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR4);
                break;
            case COLUMN_PSTATSWR5:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR5);
                break;
            case COLUMN_PSTATSWR6:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR6);
                break;
            case COLUMN_PSTATSWR7:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR7);
                break;
            case COLUMN_PSTATSWR8:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR8);
                break;
            case COLUMN_PSTATSWR9:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR9);
                break;
            case COLUMN_PSTATSWR10:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR10);
                break;
            case COLUMN_PSTATSWR11:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR11);
                break;
            case COLUMN_PSTATSWR12:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR12);
                break;
            case COLUMN_PSTATSWR13:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR13);
                break;
            case COLUMN_PSTATSWR14:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR14);
                break;
            case COLUMN_PSTATSWR15:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR15);
                break;
            case COLUMN_PSTATSWR16:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR16);
                break;
            case COLUMN_PSTATSWR17:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR17);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    case MODE_GETNEXT:
        for (request = requests; request; request = request->next) {
            table_info = netsnmp_extract_table_info(request);
	    logmsg("%s: colnum %i\n", __func__, table_info->colnum);
            table_entry = pstatsTable_get_next_entry(reginfo, request,
                                                     table_info->colnum,
                                                     table_info->indexes);

            switch (table_info->colnum) {
            case COLUMN_PSTATSINDEX:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_INTEGER,
                                           table_entry->pstatsIndex);
                break;
            case COLUMN_PSTATSDESCR:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                                         table_entry->pstatsDescr,
                                         table_entry->pstatsDescr_len);
                break;
            case COLUMN_PSTATSWR0:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR0);
                break;
            case COLUMN_PSTATSWR1:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR1);
                break;
            case COLUMN_PSTATSWR2:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR2);
                break;
            case COLUMN_PSTATSWR3:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR3);
                break;
            case COLUMN_PSTATSWR4:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR4);
                break;
            case COLUMN_PSTATSWR5:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR5);
                break;
            case COLUMN_PSTATSWR6:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR6);
                break;
            case COLUMN_PSTATSWR7:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR7);
                break;
            case COLUMN_PSTATSWR8:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR8);
                break;
            case COLUMN_PSTATSWR9:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR9);
                break;
            case COLUMN_PSTATSWR10:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR10);
                break;
            case COLUMN_PSTATSWR11:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR11);
                break;
            case COLUMN_PSTATSWR12:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR12);
                break;
            case COLUMN_PSTATSWR13:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR13);
                break;
            case COLUMN_PSTATSWR14:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR14);
                break;
            case COLUMN_PSTATSWR15:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR15);
                break;
            case COLUMN_PSTATSWR16:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR16);
                break;
            case COLUMN_PSTATSWR17:
                if (!table_entry) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer(request->requestvb, ASN_COUNTER,
                                           table_entry->pstatsWR17);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

    }
    return SNMP_ERR_NOERROR;
}

/** Initialize the pstatsTable table by defining its contents and how it's structured */
void
initialize_table_pstatsTable(void)
{
    const oid       pstatsTable_oid[] =
        { 1, 3, 6, 1, 4, 1, 96, 100, 2, 2 };
    netsnmp_handler_registration *reg;
    netsnmp_table_registration_info *table_info;

    logmsg("%s: %i\n", __func__, __LINE__);
    reg =
        netsnmp_create_handler_registration("pstatsTable",
                                            pstatsTable_handler,
                                            pstatsTable_oid,
                                            OID_LENGTH(pstatsTable_oid),
                                            HANDLER_CAN_RONLY);

    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: pstatsIndex */
                                     0);

    table_info->min_column = COLUMN_PSTATSINDEX;
    table_info->max_column = COLUMN_PSTATSWR17;

    netsnmp_register_table(reg, table_info);

    /*
     * Initialise the contents of the table here 
     */
}

/** Initializes the pstatsTable module */
void
init_pstatsTable(void)
{
    logmsg("%s: %i\n", __func__, __LINE__);
    /*
     * here we initialize all the tables we're planning on supporting 
     */
    initialize_table_pstatsTable();
}
